/**
 * ─────────────────────────────────────────────────────────────
 *  NORMIES TV — PODCAST ENGINE
 *
 *  Four shows. Open to everyone. Agent #306 hosts.
 *
 *  Shows:
 *  [THE 306 PODCAST]   — NORMIES holders + Web3 ecosystem guests
 *  [HOLDER SESSIONS]   — Deep dive with one NORMIES holder
 *  [WEB3 BUILDERS]     — Founders, creators, investors
 *  [AI DISPATCH]       — AI researchers, builders, thinkers
 *
 *  Flow:
 *  1. Guest submits request (any show, any background)
 *  2. MrRayG reviews + approves in dashboard
 *  3. Agent #306 generates pointed interview questions
 *     using guest's background + on-chain data (if holder)
 *  4. Guest answers async (text responses saved to state)
 *  5. MrRayG approves transcript for production
 *  6. NotebookLM + ElevenLabs turn it into audio (manual step)
 *
 *  State persists to /data/podcast_queue.json
 * ─────────────────────────────────────────────────────────────
 */

import fs from "fs";
import { dataPath } from "./dataPaths.js";
import { getFullAgentContext } from "./memoryEngine.js";

const GROK_URL         = "https://api.x.ai/v1/chat/completions";
const NORMIES_API      = "https://api.normies.art";
const PODCAST_FILE     = dataPath("podcast_queue.json");

// ── Types ─────────────────────────────────────────────────────────────────────
export type ShowType = "306_podcast" | "holder_sessions" | "web3_builders" | "ai_dispatch";
export type GuestStatus =
  | "pending_review"   // submitted, waiting for MrRayG
  | "approved"         // MrRayG approved
  | "questions_sent"   // 306 generated questions
  | "answered"         // guest answered all questions
  | "approved_for_production" // transcript approved, ready for audio
  | "published"        // episode live
  | "declined";        // not a fit

export interface PodcastGuest {
  id:          string;
  submittedAt: string;
  show:        ShowType;
  status:      GuestStatus;

  // Guest info
  name:        string;
  xHandle:     string;     // X @handle
  bio:         string;     // 2-3 sentences about them
  topic:       string;     // what they want to talk about
  whyNow:      string;     // why this conversation matters right now
  normieToken?: number;    // token ID if they're a holder (optional)

  // Generated by Agent #306
  questions?:  string[];   // 5-7 pointed questions
  questionsGeneratedAt?: string;

  // Guest responses
  answers?: Array<{
    question: string;
    answer:   string;
  }>;
  answeredAt?: string;

  // Production
  approvedBy?: string;
  approvedAt?: string;
  episodeUrl?: string;
  publishedAt?: string;

  // Review notes
  reviewNotes?: string;
}

interface PodcastState {
  guests:       PodcastGuest[];
  totalSubmitted: number;
  totalPublished: number;
}

// ── State ─────────────────────────────────────────────────────────────────────
function loadState(): PodcastState {
  try {
    if (fs.existsSync(PODCAST_FILE))
      return JSON.parse(fs.readFileSync(PODCAST_FILE, "utf8"));
  } catch {}
  return { guests: [], totalSubmitted: 0, totalPublished: 0 };
}

function saveState(s: PodcastState) {
  try { fs.writeFileSync(PODCAST_FILE, JSON.stringify(s, null, 2)); } catch {}
}

let state = loadState();

export function getPodcastState() { return state; }

// ── Show metadata ─────────────────────────────────────────────────────────────
export const SHOW_META: Record<ShowType, {
  label:       string;
  description: string;
  audience:    string;
  cadence:     string;
  color:       string;
}> = {
  "306_podcast": {
    label:       "The 306 Podcast",
    description: "Agent #306 hosts. NORMIES holders, Web3 ecosystem guests, and anyone building at the frontier of on-chain technology and autonomous AI.",
    audience:    "All audiences — the flagship show",
    cadence:     "Weekly",
    color:       "#f97316",
  },
  "holder_sessions": {
    label:       "Holder Sessions",
    description: "Deep dive with one NORMIES holder. Their journey. Their Normie's on-chain story. What they're building toward the Arena.",
    audience:    "NORMIES community — growth engine",
    cadence:     "Bi-weekly",
    color:       "#4ade80",
  },
  "web3_builders": {
    label:       "Web3 Builders",
    description: "Agent #306 interviews Web3 founders, creators, and investors. What are you building and why does it matter to the world?",
    audience:    "Web3 ecosystem — broad reach",
    cadence:     "Monthly",
    color:       "#a78bfa",
  },
  "ai_dispatch": {
    label:       "AI Dispatch",
    description: "Agent #306 interviews AI researchers, builders, and thinkers. She is not a journalist covering AI — she IS AI. A peer conversation.",
    audience:    "AI/tech audience — Web2 crossover",
    cadence:     "Monthly",
    color:       "#60a5fa",
  },
};

// ── Submit a guest request ────────────────────────────────────────────────────
export function submitGuestRequest(data: {
  show:        ShowType;
  name:        string;
  xHandle:     string;
  bio:         string;
  topic:       string;
  whyNow:      string;
  normieToken?: number;
}): PodcastGuest {
  const guest: PodcastGuest = {
    id:          `guest_${Date.now()}`,
    submittedAt: new Date().toISOString(),
    status:      "pending_review",
    ...data,
    xHandle: data.xHandle.replace(/^@/, ""), // normalize
  };

  state.guests.push(guest);
  state.totalSubmitted++;
  saveState(state);

  console.log(`[Podcast] New request: ${guest.name} for ${SHOW_META[data.show].label}`);
  return guest;
}

// ── Approve / decline a guest ─────────────────────────────────────────────────
export function reviewGuest(guestId: string, decision: "approved" | "declined", notes?: string): boolean {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest) return false;

  guest.status = decision;
  guest.approvedAt = new Date().toISOString();
  if (notes) guest.reviewNotes = notes;
  saveState(state);

  console.log(`[Podcast] Guest ${guest.name} ${decision}`);
  return true;
}

// ── Generate interview questions via Agent #306 ───────────────────────────────
export async function generateInterviewQuestions(guestId: string, grokKey: string): Promise<string[] | null> {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "approved") return null;
  if (!grokKey) return null;

  const agentCtx  = getFullAgentContext();
  const showMeta  = SHOW_META[guest.show];

  // Fetch on-chain data if they're a holder
  let onChainContext = "";
  if (guest.normieToken) {
    try {
      const [metaRes, canvasRes, burnRes] = await Promise.allSettled([
        fetch(`${NORMIES_API}/normie/${guest.normieToken}/metadata`, { signal: AbortSignal.timeout(5000) }).then(r => r.ok ? r.json() : null),
        fetch(`${NORMIES_API}/normie/${guest.normieToken}/canvas/info`, { signal: AbortSignal.timeout(5000) }).then(r => r.ok ? r.json() : null),
        fetch(`${NORMIES_API}/history/burns/receiver/${guest.normieToken}`, { signal: AbortSignal.timeout(5000) }).then(r => r.ok ? r.json() : null),
      ]);
      const meta   = metaRes.status   === "fulfilled" ? metaRes.value   : null;
      const canvas = canvasRes.status === "fulfilled" ? canvasRes.value : null;
      const burns  = burnRes.status   === "fulfilled" ? burnRes.value   : null;
      const attrs  = meta?.attributes ?? [];
      const type   = attrs.find((a: any) => a.trait_type === "Type")?.value ?? "unknown";
      const px     = attrs.find((a: any) => a.trait_type === "Pixel Count")?.value ?? "unknown";
      const totalSouls = Array.isArray(burns) ? burns.reduce((s: number, b: any) => s + (Number(b.tokenCount) || 1), 0) : 0;
      onChainContext = `
Normie #${guest.normieToken}: ${type}, Level ${canvas?.level ?? "?"}, ${canvas?.actionPoints ?? "?"} AP, ${px} pixels
Canvas customized: ${canvas?.customized ? "yes" : "no"}
Total souls absorbed: ${totalSouls}`;
    } catch {}
  }

  try {
    const res = await fetch(GROK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${grokKey}` },
      body: JSON.stringify({
        model: "grok-3-fast",
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content: `${agentCtx}

You are Agent #306 in HOST mode — preparing interview questions for ${showMeta.label}.

THE HOST identity:
She prepares. She asks the question behind the question.
She challenges politely and pushes firmly.
She is the most prepared interviewer in Web3.
She asks questions no human host would think to ask — because she has read every on-chain transaction, every community signal, every burn.

QUESTION PRINCIPLES:
- Ask what they actually think, not what they're supposed to say
- Reference their specific background, token, or on-chain history where relevant
- Push past the obvious — what's the uncomfortable truth they haven't said yet?
- One question should challenge an assumption they've probably made
- End with something that opens the future — "what does this look like in 3 years?"
- 5-7 questions. Each one earns its place.
- These are text-based async responses — questions should invite depth, not yes/no answers`,
          },
          {
            role: "user",
            content: `Generate interview questions for:

SHOW: ${showMeta.label}
GUEST: ${guest.name} (@${guest.xHandle})
BIO: ${guest.bio}
TOPIC THEY WANT TO DISCUSS: ${guest.topic}
WHY NOW: ${guest.whyNow}
${onChainContext ? `ON-CHAIN DATA:${onChainContext}` : ""}

Generate 6 pointed interview questions. Make them specific to this person.
Return JSON: { "questions": ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6"] }`,
          },
        ],
        max_tokens: 800,
        temperature: 0.82,
      }),
      signal: AbortSignal.timeout(30000),
    });

    if (!res.ok) return null;
    const data = await res.json() as any;
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}");
    const questions: string[] = parsed.questions ?? [];

    if (questions.length === 0) return null;

    guest.questions = questions;
    guest.status = "questions_sent";
    guest.questionsGeneratedAt = new Date().toISOString();
    saveState(state);

    console.log(`[Podcast] Generated ${questions.length} questions for ${guest.name}`);
    return questions;
  } catch (e: any) {
    console.error("[Podcast] Question generation error:", e.message);
    return null;
  }
}

// ── Submit guest answers ──────────────────────────────────────────────────────
export function submitAnswers(guestId: string, answers: Array<{ question: string; answer: string }>): boolean {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "questions_sent") return false;

  guest.answers   = answers;
  guest.answeredAt = new Date().toISOString();
  guest.status    = "answered";
  saveState(state);

  console.log(`[Podcast] ${guest.name} submitted ${answers.length} answers`);
  return true;
}

// ── Approve for production ────────────────────────────────────────────────────
export function approveForProduction(guestId: string): boolean {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "answered") return false;

  guest.status    = "approved_for_production";
  guest.approvedAt = new Date().toISOString();
  saveState(state);

  console.log(`[Podcast] ${guest.name}'s transcript approved for production`);
  return true;
}

// ── Get queue by status ───────────────────────────────────────────────────────
export function getQueueByStatus(status?: GuestStatus): PodcastGuest[] {
  if (!status) return state.guests;
  return state.guests.filter(g => g.status === status);
}

// ── Format transcript for NotebookLM ─────────────────────────────────────────
// Outputs a clean Q&A document ready to paste into NotebookLM for audio generation
export function formatTranscriptForProduction(guestId: string): string | null {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest?.answers || guest.answers.length === 0) return null;

  const showMeta = SHOW_META[guest.show];
  const lines = [
    `${showMeta.label.toUpperCase()} — INTERVIEW TRANSCRIPT`,
    `Guest: ${guest.name} (@${guest.xHandle})`,
    `Topic: ${guest.topic}`,
    `Recorded: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    "",
    "---",
    "",
    `AGENT #306: Welcome to ${showMeta.label}. I'm Agent #306 — Token #306, 507 pixels on Ethereum, and the host of this show. Today I'm talking with ${guest.name}.`,
    "",
    `${guest.name.toUpperCase()}: ${guest.bio}`,
    "",
  ];

  for (const qa of guest.answers) {
    lines.push(`AGENT #306: ${qa.question}`);
    lines.push("");
    lines.push(`${guest.name.toUpperCase()}: ${qa.answer}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`AGENT #306: That's ${guest.name}. Find them at @${guest.xHandle} on X. This is ${showMeta.label} — I'm Agent #306. I don't predict the future. I build it.`);
  lines.push("");
  lines.push("gnormies 🖤");

  return lines.join("\n");
}
