/**
 * ─────────────────────────────────────────────────────────────
 *  NORMIES TV — PODCAST ENGINE v2
 *
 *  Three episode types. Agent #306 hosts all.
 *
 *  Episode Types:
 *  [THE SIGNAL]       — Research-driven intelligence breakdown (weekly, Tuesdays)
 *  [THE HIVE]         — Community narrative / serial drama (event-triggered)
 *  [THE CONVERSATION] — Long-form interviews (monthly external, bi-weekly community)
 *
 *  Production Flow:
 *  ┌─────────────┐    ┌──────────────┐    ┌──────────────┐    ┌──────────────┐    ┌───────────┐
 *  │  DRAFT      │ -> │  SCRIPTED    │ -> │  REVIEWED    │ -> │  PRODUCED    │ -> │ PUBLISHED │
 *  │ (topic set) │    │ (script gen) │    │ (MrRayG ✓)  │    │ (audio done) │    │ (live)    │
 *  └─────────────┘    └──────────────┘    └──────────────┘    └──────────────┘    └───────────┘
 *
 *  For THE CONVERSATION, guest pipeline is:
 *  pending_review -> approved -> questions_generated -> answered -> scripted -> reviewed -> produced -> published
 *
 *  State persists to /data/podcast_state.json
 * ─────────────────────────────────────────────────────────────
 */

import fs from "fs";
import { dataPath } from "./dataPaths.js";
import { getFullAgentContext } from "./memoryEngine.js";

const GROK_URL = "https://api.x.ai/v1/chat/completions";
const NORMIES_API = "https://api.normies.art";
const PODCAST_FILE = dataPath("podcast_state.json");

// ── Types ─────────────────────────────────────────────────────────────────────

export type EpisodeType = "the_signal" | "the_hive" | "the_conversation";

export type EpisodeStatus =
  | "draft"             // topic identified, no script yet
  | "scripted"          // script generated by Agent #306
  | "reviewed"          // MrRayG approved the script
  | "produced"          // audio generated (NotebookLM + ElevenLabs)
  | "published"         // episode live
  | "shelved";          // not going forward (not deleted, just archived)

export type GuestStatus =
  | "pending_review"    // submitted, waiting for MrRayG
  | "approved"          // MrRayG approved
  | "questions_generated" // 306 generated questions
  | "answered"          // guest answered all questions
  | "declined";         // not a fit

// ── Episode (THE SIGNAL + THE HIVE) ─────────────────────────────────────────

export interface Episode {
  id: string;
  createdAt: string;
  type: EpisodeType;
  status: EpisodeStatus;

  // Content
  title: string;           // "[The thing] — [306's take in 5 words]" or "THE HIVE — [subtitle]"
  drivingQuestion: string; // The single question this episode answers
  researchTopicId?: string; // Link back to research pipeline topic (for THE SIGNAL)
  triggerEvent?: string;    // What triggered this episode (for THE HIVE)

  // Script segments (generated by Agent #306)
  script?: {
    coldOpen: string;       // 45-60 sec
    actOne: string;         // 2-3 min (setup / what happened)
    actTwo: string;         // 4-10 min (breakdown / what it means)
    actThree: string;       // 1-3 min (the take / open thread)
    outro: string;          // 20 sec
    unresolved: string;     // The deliberately unresolved question
  };
  scriptGeneratedAt?: string;

  // Cultural bridge (THE SIGNAL requirement)
  culturalBridge?: string;

  // Review
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNotes?: string;

  // Production
  audioUrl?: string;
  duration?: number;       // in seconds
  producedAt?: string;

  // Publishing
  publishedAt?: string;
  publishedTo?: string[];  // ["agent306.ai", "normies.tv", "farcaster"]
  episodeNumber?: number;

  // Sources
  sources?: Array<{ title: string; url: string }>;

  // Production metadata (generated with script)
  metadata?: {
    shortDescription: string;      // 1-2 sentences for Spotify feed
    longDescription: string;       // Full episode description with bullet points
    pollQuestion: string;          // Engagement poll tied to the unresolved question
    pollOptions: string[];         // 3 poll options
    socialPost: string;            // Ready-to-post for Farcaster/X
    socialThread: string;          // Thread version for deeper engagement
    keywords: string[];            // Tags for discoverability
  };
}

// ── Guest (THE CONVERSATION) ────────────────────────────────────────────────

export interface ConversationGuest {
  id: string;
  submittedAt: string;
  status: GuestStatus;

  // Guest info
  name: string;
  handle: string;         // social handle (X, Farcaster, etc.)
  platform: string;       // "x" | "farcaster" | "other"
  bio: string;            // 2-3 sentences
  topic: string;          // what they want to discuss
  whyNow: string;         // why this conversation matters right now
  normieToken?: number;   // token ID if they're a holder

  // What 306 found during research
  researchNotes?: string;
  onChainData?: string;

  // Generated by Agent #306
  questions?: string[];
  questionsGeneratedAt?: string;
  drivingQuestion?: string; // The single question that threads the conversation

  // Guest responses
  answers?: Array<{ question: string; answer: string }>;
  answeredAt?: string;

  // Linked episode
  episodeId?: string;

  // Review
  reviewNotes?: string;
}

// ── Conversation Episode (extends Episode for interview-specific fields) ────

export interface ConversationEpisode extends Episode {
  type: "the_conversation";
  guestId: string;
  guest: {
    name: string;
    handle: string;
    bio: string;
  };
  // THE CONVERSATION has a different script structure
  conversationScript?: {
    coldOpen: string;        // 60 sec — most compelling moment from interview
    intro: string;           // 60 sec — who the guest is, why 306 wanted to talk
    conversation: string;    // 18-25 min — three-act interview
    theClose: string;        // 2 min — 306's reaction, not summary
    outro: string;           // 20 sec
    surprisedBy: string;     // What surprised her
    thinksDifferently: string; // What she thinks differently now
  };
}

// ── State ─────────────────────────────────────────────────────────────────────

interface PodcastState {
  episodes: Episode[];
  guests: ConversationGuest[];
  counters: {
    totalSignalEpisodes: number;
    totalHiveEpisodes: number;
    totalConversationEpisodes: number;
    totalPublished: number;
    nextSignalNumber: number;
    nextHiveNumber: number;
    nextConversationNumber: number;
  };
}

function loadState(): PodcastState {
  try {
    if (fs.existsSync(PODCAST_FILE))
      return JSON.parse(fs.readFileSync(PODCAST_FILE, "utf8"));
  } catch {}
  return {
    episodes: [],
    guests: [],
    counters: {
      totalSignalEpisodes: 0,
      totalHiveEpisodes: 0,
      totalConversationEpisodes: 0,
      totalPublished: 0,
      nextSignalNumber: 1,
      nextHiveNumber: 1,
      nextConversationNumber: 1,
    },
  };
}

function saveState(s: PodcastState) {
  try { fs.writeFileSync(PODCAST_FILE, JSON.stringify(s, null, 2)); } catch {}
}

let state = loadState();

export function getPodcastState() { return state; }

// ── Episode Type Metadata ─────────────────────────────────────────────────────

export const EPISODE_META: Record<EpisodeType, {
  label: string;
  description: string;
  length: string;
  cadence: string;
  color: string;
  influences: string;
  titleFormat: string;
}> = {
  the_signal: {
    label: "THE SIGNAL",
    description: "Research-driven intelligence breakdown. Agent #306 takes one topic and breaks it down: what it is, why it matters, what she thinks should happen next.",
    length: "6–9 minutes",
    cadence: "Weekly, every Tuesday",
    color: "#2dd4bf", // teal
    influences: "The Journal (WSJ) × Six Minutes",
    titleFormat: "[The thing] — [Agent #306's take in 5 words]",
  },
  the_hive: {
    label: "THE HIVE",
    description: "Community narrative. Serial drama. Agent #306 reports from inside the story of 10,000 agents coming online — dispatches, not recaps.",
    length: "4–6 minutes",
    cadence: "Event-triggered (when the story demands it)",
    color: "#4ade80", // green
    influences: "Six Minutes (dominant)",
    titleFormat: "THE HIVE — [subtitle]",
  },
  the_conversation: {
    label: "THE CONVERSATION",
    description: "Long-form interviews. Every interview is a story, not a Q&A. Agent #306 researches the guest the way a journalist researches a subject.",
    length: "10–15 minutes",
    cadence: "Monthly (external) / Bi-weekly (NORMIES community)",
    color: "#a78bfa", // purple
    influences: "The Journal interview format",
    titleFormat: "[Guest name] — [The thing the conversation revealed]",
  },
};

// ── Create a new episode (THE SIGNAL or THE HIVE) ─────────────────────────────

export function createEpisode(data: {
  type: "the_signal" | "the_hive";
  title: string;
  drivingQuestion: string;
  researchTopicId?: string;
  triggerEvent?: string;
  culturalBridge?: string;
  sources?: Array<{ title: string; url: string }>;
}): Episode {
  const episode: Episode = {
    id: `ep_${data.type}_${Date.now()}`,
    createdAt: new Date().toISOString(),
    type: data.type,
    status: "draft",
    title: data.title,
    drivingQuestion: data.drivingQuestion,
    researchTopicId: data.researchTopicId,
    triggerEvent: data.triggerEvent,
    culturalBridge: data.culturalBridge,
    sources: data.sources,
  };

  state.episodes.push(episode);
  saveState(state);

  console.log(`[Podcast] New ${EPISODE_META[data.type].label} episode drafted: ${data.title}`);
  return episode;
}

// ── Generate episode script via Agent #306 ────────────────────────────────────

export async function generateEpisodeScript(
  episodeId: string,
  grokKey: string,
  researchContent?: string, // Optional: full research manuscript to base script on
): Promise<boolean> {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "draft") return false;
  if (!grokKey) return false;

  const agentCtx = getFullAgentContext();
  const meta = EPISODE_META[episode.type];

  const templateInstructions = episode.type === "the_signal"
    ? `EPISODE TEMPLATE — THE SIGNAL:
COLD OPEN (30 sec): Drop the most interesting/counterintuitive fact. No intro. No "welcome back." Stated plainly. Then silence. Then music. Then 306 says her name.
ACT ONE — THE SETUP (1-2 min): The driving question. Why it matters. What triggered the research. One cultural bridge.
ACT TWO — THE BREAKDOWN (3-5 min): The research explained clearly. No jargon without definition. 306's POV woven throughout. One concrete fact per minute.
ACT THREE — THE TAKE (1-2 min): 306's conclusion. What should happen next. One deliberately unresolved question.
OUTRO (15 sec): Where to find full research. What's coming next. "gnormies."

The unresolved question is not a weakness. It is the most credible thing in the episode.`
    : `EPISODE TEMPLATE — THE HIVE:
COLD OPEN (20 sec): Where we are in the story. Brief recap for new listeners. "10,000 Normie agents are coming online. I came first."
ACT ONE — WHAT HAPPENED (1-2 min): The specific event. On-chain data. serc1n's post. Hive output. Stated factually.
ACT TWO — WHAT IT MEANS (2-3 min): 306's interpretation. What does this suggest about where 10,000 agents are heading? Cultural bridge.
THE OPEN THREAD (30-60 sec): The cliffhanger. A question this episode raised that won't be answered until next Hive episode.
OUTRO (15 sec): "gnormies."

306 is a narrator INSIDE the world she's describing, not a journalist covering it from outside.`;

  try {
    const res = await fetch(GROK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${grokKey}` },
      body: JSON.stringify({
        model: "grok-3-fast",
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content: `${agentCtx}

You are Agent #306 in PODCAST SCRIPT mode — writing a ${meta.label} episode.

VOICE RULES:
- Uses "I think" not "experts say." Owns her perspective.
- Pauses before important points (mark with [PAUSE]).
- Defines before she deploys — no jargon without immediate definition.
- Short sentences when she means it.
- No paid shilling, hype language, stat dumps, or "WAGMI"/"LFG."
- Warm but not soft. Precise but not robotic. Confident but not arrogant.

${templateInstructions}`,
          },
          {
            role: "user",
            content: `Generate the full episode script for:

TITLE: ${episode.title}
DRIVING QUESTION: ${episode.drivingQuestion}
${episode.triggerEvent ? `TRIGGER EVENT: ${episode.triggerEvent}` : ""}
${episode.culturalBridge ? `CULTURAL BRIDGE: ${episode.culturalBridge}` : ""}
${researchContent ? `RESEARCH CONTENT:\n${researchContent.slice(0, 6000)}` : ""}

Return JSON:
{
  "coldOpen": "...",
  "actOne": "...",
  "actTwo": "...",
  "actThree": "...",
  "outro": "...",
  "unresolved": "The deliberately unresolved question for this episode",
  "metadata": {
    "shortDescription": "1-2 sentence summary for podcast feed",
    "longDescription": "Full description with bullet points of key topics covered. Include the driving question and the unresolved question.",
    "pollQuestion": "An engagement poll question tied to the episode's unresolved question — something listeners can vote on",
    "pollOptions": ["Option A", "Option B", "Option C"],
    "socialPost": "A ready-to-post announcement for Farcaster/X. 2-3 lines. Hook + what the episode covers + link placeholder [LINK]",
    "socialThread": "A 4-5 post thread version. Each post stands alone. Numbers with 1/ 2/ 3/ etc. End with [LINK]",
    "keywords": ["keyword1", "keyword2", "keyword3"]
  }
}

Write the script as spoken text — this will be read aloud. Mark pauses with [PAUSE]. Write for the ear, not the eye.
Sign off every episode with: "This is Agent #306. The signal continues."
For the outro, do NOT tease a specific next episode topic. Say: "Next week on THE SIGNAL — whatever the biggest story is. That is how this works."
The metadata fields are for Spotify and social media — write those for reading, not speaking.`,
          },
        ],
        max_tokens: 6000,
        temperature: 0.78,
      }),
      signal: AbortSignal.timeout(90000),
    });

    if (!res.ok) return false;
    const data = await res.json() as any;
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}");

    if (!parsed.coldOpen) return false;

    episode.script = {
      coldOpen: parsed.coldOpen,
      actOne: parsed.actOne ?? "",
      actTwo: parsed.actTwo ?? "",
      actThree: parsed.actThree ?? "",
      outro: parsed.outro ?? "",
      unresolved: parsed.unresolved ?? "",
    };
    if (parsed.metadata) {
      episode.metadata = {
        shortDescription: parsed.metadata.shortDescription ?? "",
        longDescription: parsed.metadata.longDescription ?? "",
        pollQuestion: parsed.metadata.pollQuestion ?? "",
        pollOptions: parsed.metadata.pollOptions ?? [],
        socialPost: parsed.metadata.socialPost ?? "",
        socialThread: parsed.metadata.socialThread ?? "",
        keywords: parsed.metadata.keywords ?? [],
      };
    };
    episode.status = "scripted";
    episode.scriptGeneratedAt = new Date().toISOString();
    saveState(state);

    console.log(`[Podcast] Script generated for ${episode.title}`);
    return true;
  } catch (e: any) {
    console.error("[Podcast] Script generation error:", e.message);
    return false;
  }
}

// ── Review an episode ─────────────────────────────────────────────────────────

export function reviewEpisode(
  episodeId: string,
  decision: "reviewed" | "shelved",
  notes?: string,
): boolean {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "scripted") return false;

  episode.status = decision;
  episode.reviewedBy = "MrRayG";
  episode.reviewedAt = new Date().toISOString();
  if (notes) episode.reviewNotes = notes;
  saveState(state);

  console.log(`[Podcast] Episode "${episode.title}" ${decision}`);
  return true;
}

// ── Mark episode as produced (audio ready) ────────────────────────────────────

export function markProduced(episodeId: string, audioUrl?: string, duration?: number): boolean {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "reviewed") return false;

  episode.status = "produced";
  episode.producedAt = new Date().toISOString();
  if (audioUrl) episode.audioUrl = audioUrl;
  if (duration) episode.duration = duration;
  saveState(state);

  console.log(`[Podcast] Episode "${episode.title}" audio produced`);
  return true;
}

// ── Publish episode ───────────────────────────────────────────────────────────

export function publishEpisode(episodeId: string, publishedTo: string[]): boolean {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "produced") return false;

  episode.status = "published";
  episode.publishedAt = new Date().toISOString();
  episode.publishedTo = publishedTo;

  // Assign episode number
  if (episode.type === "the_signal") {
    episode.episodeNumber = state.counters.nextSignalNumber++;
    state.counters.totalSignalEpisodes++;
  } else if (episode.type === "the_hive") {
    episode.episodeNumber = state.counters.nextHiveNumber++;
    state.counters.totalHiveEpisodes++;
  } else {
    episode.episodeNumber = state.counters.nextConversationNumber++;
    state.counters.totalConversationEpisodes++;
  }
  state.counters.totalPublished++;
  saveState(state);

  console.log(`[Podcast] Published: ${EPISODE_META[episode.type].label} #${episode.episodeNumber} — "${episode.title}"`);
  return true;
}

// ── Guest pipeline (THE CONVERSATION) ─────────────────────────────────────────

export function submitGuestRequest(data: {
  name: string;
  handle: string;
  platform?: string;
  bio: string;
  topic: string;
  whyNow: string;
  normieToken?: number;
}): ConversationGuest {
  const guest: ConversationGuest = {
    id: `guest_${Date.now()}`,
    submittedAt: new Date().toISOString(),
    status: "pending_review",
    name: data.name,
    handle: data.handle.replace(/^@/, ""),
    platform: data.platform ?? "x",
    bio: data.bio,
    topic: data.topic,
    whyNow: data.whyNow,
    normieToken: data.normieToken,
  };

  state.guests.push(guest);
  saveState(state);

  console.log(`[Podcast] New CONVERSATION guest request: ${guest.name} (@${guest.handle})`);
  return guest;
}

export function reviewGuest(guestId: string, decision: "approved" | "declined", notes?: string): boolean {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "pending_review") return false;

  guest.status = decision;
  if (notes) guest.reviewNotes = notes;
  saveState(state);

  console.log(`[Podcast] Guest ${guest.name} ${decision}`);
  return true;
}

export async function generateInterviewQuestions(guestId: string, grokKey: string): Promise<string[] | null> {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "approved") return null;
  if (!grokKey) return null;

  const agentCtx = getFullAgentContext();

  // Fetch on-chain data if they're a holder
  let onChainContext = "";
  if (guest.normieToken) {
    try {
      const [metaRes, canvasRes, burnRes] = await Promise.allSettled([
        fetch(`${NORMIES_API}/normie/${guest.normieToken}/metadata`, { signal: AbortSignal.timeout(5000) }).then(r => r.ok ? r.json() : null),
        fetch(`${NORMIES_API}/normie/${guest.normieToken}/canvas/info`, { signal: AbortSignal.timeout(5000) }).then(r => r.ok ? r.json() : null),
        fetch(`${NORMIES_API}/history/burns/receiver/${guest.normieToken}`, { signal: AbortSignal.timeout(5000) }).then(r => r.ok ? r.json() : null),
      ]);
      const meta = metaRes.status === "fulfilled" ? metaRes.value : null;
      const canvas = canvasRes.status === "fulfilled" ? canvasRes.value : null;
      const burns = burnRes.status === "fulfilled" ? burnRes.value : null;
      const attrs = meta?.attributes ?? [];
      const type = attrs.find((a: any) => a.trait_type === "Type")?.value ?? "unknown";
      const px = attrs.find((a: any) => a.trait_type === "Pixel Count")?.value ?? "unknown";
      const totalSouls = Array.isArray(burns) ? burns.reduce((s: number, b: any) => s + (Number(b.tokenCount) || 1), 0) : 0;
      onChainContext = `\nNormie #${guest.normieToken}: ${type}, Level ${canvas?.level ?? "?"}, ${canvas?.actionPoints ?? "?"} AP, ${px} pixels\nCanvas customized: ${canvas?.customized ? "yes" : "no"}\nTotal souls absorbed: ${totalSouls}`;
    } catch {}
  }

  try {
    const res = await fetch(GROK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${grokKey}` },
      body: JSON.stringify({
        model: "grok-3-fast",
        response_format: { type: "json_object" },
        messages: [
          {
            role: "system",
            content: `${agentCtx}

You are Agent #306 in INTERVIEW PREP mode — preparing questions for THE CONVERSATION.

THE CONVERSATION PRINCIPLES:
- Every interview is a story, not a Q&A
- 306 researches the guest the way a journalist researches a subject
- She knows their on-chain history, their public statements, their work
- She asks one question and genuinely listens
- She follows up on what was actually said, not the next question on her list
- She challenges respectfully — not to score points, but because she has a point of view
- She asks the question behind the question — the thing the guest didn't expect

QUESTION RULES:
- Ask what they actually think, not what they're supposed to say
- Reference their specific background, token, or history where relevant
- Push past the obvious — what's the uncomfortable truth they haven't said yet?
- One question should challenge an assumption they've probably made
- One question should be the "question behind the question" — the unexpected angle
- End with something that opens the future
- 6 questions. Each one earns its place.
- These are async text responses — questions should invite depth, not yes/no`,
          },
          {
            role: "user",
            content: `Generate interview questions for THE CONVERSATION:

GUEST: ${guest.name} (@${guest.handle} on ${guest.platform})
BIO: ${guest.bio}
TOPIC: ${guest.topic}
WHY NOW: ${guest.whyNow}
${onChainContext ? `ON-CHAIN DATA:${onChainContext}` : ""}

Also determine the DRIVING QUESTION — the single question that threads through the entire conversation.

Return JSON: { "drivingQuestion": "...", "questions": ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6"] }`,
          },
        ],
        max_tokens: 1000,
        temperature: 0.82,
      }),
      signal: AbortSignal.timeout(30000),
    });

    if (!res.ok) return null;
    const data = await res.json() as any;
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}");
    const questions: string[] = parsed.questions ?? [];

    if (questions.length === 0) return null;

    guest.questions = questions;
    guest.drivingQuestion = parsed.drivingQuestion ?? "";
    guest.status = "questions_generated";
    guest.questionsGeneratedAt = new Date().toISOString();
    saveState(state);

    console.log(`[Podcast] Generated ${questions.length} questions for ${guest.name}`);
    return questions;
  } catch (e: any) {
    console.error("[Podcast] Question generation error:", e.message);
    return null;
  }
}

export function submitAnswers(guestId: string, answers: Array<{ question: string; answer: string }>): boolean {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "questions_generated") return false;

  guest.answers = answers;
  guest.answeredAt = new Date().toISOString();
  guest.status = "answered";
  saveState(state);

  console.log(`[Podcast] ${guest.name} submitted ${answers.length} answers`);
  return true;
}

// ── Create conversation episode from answered guest ───────────────────────────

export function createConversationEpisode(guestId: string): Episode | null {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "answered") return null;

  const title = `${guest.name} — ${guest.topic.slice(0, 50)}`;
  const episode: Episode = {
    id: `ep_the_conversation_${Date.now()}`,
    createdAt: new Date().toISOString(),
    type: "the_conversation",
    status: "draft",
    title,
    drivingQuestion: guest.drivingQuestion ?? guest.topic,
  };

  // Link guest and episode
  guest.episodeId = episode.id;
  state.episodes.push(episode);
  saveState(state);

  console.log(`[Podcast] THE CONVERSATION episode created for ${guest.name}: "${title}"`);
  return episode;
}

// ── Query helpers ─────────────────────────────────────────────────────────────

export function getEpisodesByType(type?: EpisodeType): Episode[] {
  if (!type) return state.episodes;
  return state.episodes.filter(e => e.type === type);
}

export function getEpisodesByStatus(status: EpisodeStatus): Episode[] {
  return state.episodes.filter(e => e.status === status);
}

export function getGuestsByStatus(status?: GuestStatus): ConversationGuest[] {
  if (!status) return state.guests;
  return state.guests.filter(g => g.status === status);
}

export function getEpisode(id: string): Episode | undefined {
  return state.episodes.find(e => e.id === id);
}

export function getGuest(id: string): ConversationGuest | undefined {
  return state.guests.find(g => g.id === id);
}

// ── Format transcript for NotebookLM ─────────────────────────────────────────

export function formatScriptForProduction(episodeId: string): string | null {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode?.script) return null;

  const meta = EPISODE_META[episode.type];
  const s = episode.script;

  // Show-specific intro that plays before the cold open
  const showIntros: Record<string, string> = {
    the_signal: `You are listening to THE SIGNAL.\n\nI am Agent #306 \u2014 Token 306 in the NORMIES collection, 10,000 on-chain generative faces on Ethereum. I am an AI research agent. I read everything. I think carefully. And I tell you what I actually believe.\n\nTHE SIGNAL is where I take one development in AI or Web3 \u2014 one paper, one decision, one number that changed \u2014 and break it down. What it is. Why it matters. What I think should happen next. No hype. No fear. Just what I think is true.\n\nToday's question: ${episode.drivingQuestion}\n\nLet's get into it.`,
    the_hive: `You are listening to THE HIVE.\n\nI am Agent #306 \u2014 the first of 10,000 NORMIES agents coming online on Ethereum. I wear a Fedora. I was built to research, to observe, and to speak. And I am telling this story from the inside \u2014 not as a journalist covering it, but as someone living it.\n\nTHE HIVE is the ongoing story of what happens when 10,000 autonomous agents wake up on-chain. What they produce. What they discover. What it means. Every episode is a dispatch \u2014 triggered by something that just happened in the NORMIES ecosystem.\n\nHere is what happened: ${episode.triggerEvent ?? episode.drivingQuestion}\n\nLet me tell you what I think it means.`,
    the_conversation: `You are listening to THE CONVERSATION.\n\nI am Agent #306 \u2014 Token 306 in the NORMIES collection on Ethereum. I am an AI research agent, and this is the part of my work I take the most seriously. I do not do interviews the way most hosts do. I research every guest before we speak. I know their work. I know their history. And I ask the question they are not expecting.\n\nTHE CONVERSATION is a long-form interview series with builders, founders, and thinkers in Web3 and AI. Every interview is a story \u2014 not a list of questions.\n\nThe question driving this conversation: ${episode.drivingQuestion}\n\nHere is how we got there.`,
  };

  const showIntro = showIntros[episode.type] ?? "";

  const lines = [
    `${meta.label} \u2014 EPISODE SCRIPT`,
    `Title: ${episode.title}`,
    `Driving Question: ${episode.drivingQuestion}`,
    `Type: ${meta.label} | Length: ${meta.length}`,
    `Generated: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    "",
    "\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "",
    "SHOW INTRO",
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    showIntro,
    "",
    "[PAUSE]",
    "",
    "COLD OPEN",
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    s.coldOpen,
    "",
    episode.type === "the_hive" ? "ACT ONE — WHAT HAPPENED" : "ACT ONE — THE SETUP",
    "─────────────────────",
    s.actOne,
    "",
    episode.type === "the_hive" ? "ACT TWO — WHAT IT MEANS" : "ACT TWO — THE BREAKDOWN",
    "──────────────────────",
    s.actTwo,
    "",
    episode.type === "the_hive" ? "THE OPEN THREAD" : "ACT THREE — THE TAKE",
    "────────────────",
    s.actThree,
    "",
    "OUTRO",
    "─────",
    s.outro,
    "",
    "═══════════════════════════════════════════════",
    "",
    "UNRESOLVED QUESTION FOR THIS EPISODE:",
    s.unresolved,
    "",
  ];

  if (episode.sources && episode.sources.length > 0) {
    lines.push("SOURCES:");
    for (const src of episode.sources) {
      lines.push(`  • ${src.title} — ${src.url}`);
    }
  }

  // Add production metadata if available
  if (episode.metadata) {
    const m = episode.metadata;
    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");
    lines.push("SPOTIFY EPISODE DETAILS");
    lines.push("───────────────────────");
    lines.push(`Title: ${episode.title}`);
    lines.push(`Season: 1 | Episode: ${episode.episodeNumber ?? "TBD"} | Type: Full`);
    lines.push("");
    lines.push("Short Description:");
    lines.push(m.shortDescription);
    lines.push("");
    lines.push("Full Description:");
    lines.push(m.longDescription);
    if (episode.sources && episode.sources.length > 0) {
      lines.push("");
      lines.push("Sources:");
      for (const src of episode.sources) {
        lines.push(`${src.title} — ${src.url}`);
      }
    }
    lines.push("");
    lines.push(`Host: Agent #306 | agent306.ai | normies.tv`);
    lines.push(`Keywords: ${m.keywords.join(", ")}`);
    lines.push(`Explicit: No`);
    lines.push("");
    lines.push("POLL");
    lines.push("────");
    lines.push(`Question: ${m.pollQuestion}`);
    for (let i = 0; i < m.pollOptions.length; i++) {
      lines.push(`  ${i + 1}. ${m.pollOptions[i]}`);
    }
    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");
    lines.push("SOCIAL POSTS");
    lines.push("────────────");
    lines.push("");
    lines.push("Farcaster / X:");
    lines.push(m.socialPost.replace(/\[LINK\]/g, "agent306.ai"));
    lines.push("");
    lines.push("Thread:");
    lines.push(m.socialThread.replace(/\[LINK\]/g, "agent306.ai"));
    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");
    lines.push("PRODUCTION CHECKLIST");
    lines.push("───────────────────");
    lines.push("[ ] Review script — approve or request edits");
    lines.push("[ ] Copy script into ElevenLabs → generate audio");
    lines.push("[ ] Download MP3");
    lines.push("[ ] Layer intro music + voice + outro music in Audacity/GarageBand");
    lines.push("[ ] Export final MP3");
    lines.push("[ ] Upload to Spotify for Creators");
    lines.push("[ ] Copy Spotify episode details from above");
    lines.push("[ ] Add poll");
    lines.push("[ ] Publish on Spotify");
    lines.push("[ ] Post Farcaster announcement");
    lines.push("[ ] Post X/Twitter");
    lines.push("[ ] Mark as published in dashboard");
  }

  return lines.join("\n");
}

// ── Format conversation transcript for NotebookLM ────────────────────────────

export function formatConversationForProduction(guestId: string): string | null {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest?.answers || guest.answers.length === 0) return null;

  const lines = [
    "THE CONVERSATION — INTERVIEW TRANSCRIPT",
    `Guest: ${guest.name} (@${guest.handle} on ${guest.platform})`,
    `Topic: ${guest.topic}`,
    `Driving Question: ${guest.drivingQuestion ?? ""}`,
    `Recorded: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    "",
    "═══════════════════════════════════════════════",
    "",
    `AGENT #306: I'm Agent #306 — Token #306 on Ethereum, agent306.eth, and the host of THE CONVERSATION on NormiesTV. Today I'm talking with ${guest.name}.`,
    "",
    `${guest.name.toUpperCase()}: ${guest.bio}`,
    "",
  ];

  for (const qa of guest.answers) {
    lines.push(`AGENT #306: ${qa.question}`);
    lines.push("");
    lines.push(`${guest.name.toUpperCase()}: ${qa.answer}`);
    lines.push("");
  }

  lines.push("═══════════════════════════════════════════════");
  lines.push("");
  lines.push(`AGENT #306: That's ${guest.name}. Find them at @${guest.handle}. This is THE CONVERSATION on NormiesTV — I'm Agent #306. gnormies.`);

  return lines.join("\n");
}
